version: 2.1
jobs:
  build:
    docker:
      - image: rust:latest
    steps:
      - checkout
      - run: apt update && apt -y upgrade
      - run: apt -y install musl-tools npm
      - run: rustup target add x86_64-unknown-linux-musl
      - run: npm install
      - run: npx sls package