# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: rust:latest
    steps:
      - run:
          name: Build Rust
          command: |
            ls
            pwd
            cargo build --verbose
            cargo test --verbose